// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file meta/v1/meta.proto (package meta.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file meta/v1/meta.proto.
 */
export const file_meta_v1_meta: GenFile = /*@__PURE__*/
  fileDesc("ChJtZXRhL3YxL21ldGEucHJvdG8SB21ldGEudjEidAoIUmVzb3VyY2USCgoCaWQYASABKAkSLQoGbGFiZWxzGAIgAygLMh0ubWV0YS52MS5SZXNvdXJjZS5MYWJlbHNFbnRyeRotCgtMYWJlbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBItoCCg9Mb2dFdmVudFJlcXVlc3QSLQoFbGV2ZWwYASABKA4yHi5tZXRhLnYxLkxvZ0V2ZW50UmVxdWVzdC5MZXZlbBIPCgdtZXNzYWdlGAIgASgJEg4KBnNvdXJjZRgDIAEoCRItCgl0aW1lc3RhbXAYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjYKB2NvbnRleHQYBSADKAsyJS5tZXRhLnYxLkxvZ0V2ZW50UmVxdWVzdC5Db250ZXh0RW50cnkaLgoMQ29udGV4dEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiYAoFTGV2ZWwSDwoLTEVWRUxfREVCVUcQABIOCgpMRVZFTF9JTkZPEAESEQoNTEVWRUxfV0FSTklORxACEg8KC0xFVkVMX0VSUk9SEAMSEgoOTEVWRUxfQ1JJVElDQUwQBCI3ChJHZXRNZXRhZGF0YVJlcXVlc3QSEwoLcmVzb3VyY2VfaWQYASABKAkSDAoEa2V5cxgCIAMoCSKZAQoTR2V0TWV0YWRhdGFSZXNwb25zZRITCgtyZXNvdXJjZV9pZBgBIAEoCRI8CghtZXRhZGF0YRgCIAMoCzIqLm1ldGEudjEuR2V0TWV0YWRhdGFSZXNwb25zZS5NZXRhZGF0YUVudHJ5Gi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKyAQoVVXBkYXRlTWV0YWRhdGFSZXF1ZXN0EhMKC3Jlc291cmNlX2lkGAEgASgJEj4KCG1ldGFkYXRhGAIgAygLMiwubWV0YS52MS5VcGRhdGVNZXRhZGF0YVJlcXVlc3QuTWV0YWRhdGFFbnRyeRITCgtyZW1vdmVfa2V5cxgDIAMoCRovCg1NZXRhZGF0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEisAEKFlVwZGF0ZU1ldGFkYXRhUmVzcG9uc2USEwoLcmVzb3VyY2VfaWQYASABKAkSPwoIbWV0YWRhdGEYAiADKAsyLS5tZXRhLnYxLlVwZGF0ZU1ldGFkYXRhUmVzcG9uc2UuTWV0YWRhdGFFbnRyeRIPCgdzdWNjZXNzGAMgASgIGi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASqCAQoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEhEKDVNUQVRVU19BQ1RJVkUQARITCg9TVEFUVVNfSU5BQ1RJVkUQAhISCg5TVEFUVVNfREVMRVRFRBADEhAKDFNUQVRVU19EUkFGVBAEEhIKDlNUQVRVU19QRU5ESU5HEAUyrgEKD01ldGFkYXRhU2VydmljZRJICgtHZXRNZXRhZGF0YRIbLm1ldGEudjEuR2V0TWV0YWRhdGFSZXF1ZXN0GhwubWV0YS52MS5HZXRNZXRhZGF0YVJlc3BvbnNlElEKDlVwZGF0ZU1ldGFkYXRhEh4ubWV0YS52MS5VcGRhdGVNZXRhZGF0YVJlcXVlc3QaHy5tZXRhLnYxLlVwZGF0ZU1ldGFkYXRhUmVzcG9uc2VCIFoeZ2l0aHViLmNvbS9leGFtcGxlL2FwaS9tZXRhL3YxYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_protobuf_struct]);

/**
 * Resource represents a generic data entity
 *
 * @generated from message meta.v1.Resource
 */
export type Resource = Message<"meta.v1.Resource"> & {
  /**
   * Unique identifier
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Key-value metadata
   *
   * @generated from field: map<string, string> labels = 2;
   */
  labels: { [key: string]: string };
};

/**
 * Describes the message meta.v1.Resource.
 * Use `create(ResourceSchema)` to create a new message.
 */
export const ResourceSchema: GenMessage<Resource> = /*@__PURE__*/
  messageDesc(file_meta_v1_meta, 0);

/**
 * LogEventRequest for logging system events
 *
 * @generated from message meta.v1.LogEventRequest
 */
export type LogEventRequest = Message<"meta.v1.LogEventRequest"> & {
  /**
   * Event level
   *
   * @generated from field: meta.v1.LogEventRequest.Level level = 1;
   */
  level: LogEventRequest_Level;

  /**
   * Event message
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Event source
   *
   * @generated from field: string source = 3;
   */
  source: string;

  /**
   * Event timestamp
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * Event context data
   *
   * @generated from field: map<string, string> context = 5;
   */
  context: { [key: string]: string };
};

/**
 * Describes the message meta.v1.LogEventRequest.
 * Use `create(LogEventRequestSchema)` to create a new message.
 */
export const LogEventRequestSchema: GenMessage<LogEventRequest> = /*@__PURE__*/
  messageDesc(file_meta_v1_meta, 1);

/**
 * Severity level
 *
 * @generated from enum meta.v1.LogEventRequest.Level
 */
export enum LogEventRequest_Level {
  /**
   * @generated from enum value: LEVEL_DEBUG = 0;
   */
  DEBUG = 0,

  /**
   * @generated from enum value: LEVEL_INFO = 1;
   */
  INFO = 1,

  /**
   * @generated from enum value: LEVEL_WARNING = 2;
   */
  WARNING = 2,

  /**
   * @generated from enum value: LEVEL_ERROR = 3;
   */
  ERROR = 3,

  /**
   * @generated from enum value: LEVEL_CRITICAL = 4;
   */
  CRITICAL = 4,
}

/**
 * Describes the enum meta.v1.LogEventRequest.Level.
 */
export const LogEventRequest_LevelSchema: GenEnum<LogEventRequest_Level> = /*@__PURE__*/
  enumDesc(file_meta_v1_meta, 1, 0);

/**
 * GetMetadataRequest for retrieving metadata
 *
 * @generated from message meta.v1.GetMetadataRequest
 */
export type GetMetadataRequest = Message<"meta.v1.GetMetadataRequest"> & {
  /**
   * Resource identifier
   *
   * @generated from field: string resource_id = 1;
   */
  resourceId: string;

  /**
   * Metadata keys to retrieve (empty means all)
   *
   * @generated from field: repeated string keys = 2;
   */
  keys: string[];
};

/**
 * Describes the message meta.v1.GetMetadataRequest.
 * Use `create(GetMetadataRequestSchema)` to create a new message.
 */
export const GetMetadataRequestSchema: GenMessage<GetMetadataRequest> = /*@__PURE__*/
  messageDesc(file_meta_v1_meta, 2);

/**
 * GetMetadataResponse containing metadata information
 *
 * @generated from message meta.v1.GetMetadataResponse
 */
export type GetMetadataResponse = Message<"meta.v1.GetMetadataResponse"> & {
  /**
   * Resource identifier
   *
   * @generated from field: string resource_id = 1;
   */
  resourceId: string;

  /**
   * Metadata key-value pairs
   *
   * @generated from field: map<string, string> metadata = 2;
   */
  metadata: { [key: string]: string };
};

/**
 * Describes the message meta.v1.GetMetadataResponse.
 * Use `create(GetMetadataResponseSchema)` to create a new message.
 */
export const GetMetadataResponseSchema: GenMessage<GetMetadataResponse> = /*@__PURE__*/
  messageDesc(file_meta_v1_meta, 3);

/**
 * UpdateMetadataRequest for modifying metadata
 *
 * @generated from message meta.v1.UpdateMetadataRequest
 */
export type UpdateMetadataRequest = Message<"meta.v1.UpdateMetadataRequest"> & {
  /**
   * Resource identifier
   *
   * @generated from field: string resource_id = 1;
   */
  resourceId: string;

  /**
   * Metadata to update
   *
   * @generated from field: map<string, string> metadata = 2;
   */
  metadata: { [key: string]: string };

  /**
   * Keys to remove
   *
   * @generated from field: repeated string remove_keys = 3;
   */
  removeKeys: string[];
};

/**
 * Describes the message meta.v1.UpdateMetadataRequest.
 * Use `create(UpdateMetadataRequestSchema)` to create a new message.
 */
export const UpdateMetadataRequestSchema: GenMessage<UpdateMetadataRequest> = /*@__PURE__*/
  messageDesc(file_meta_v1_meta, 4);

/**
 * UpdateMetadataResponse after metadata modification
 *
 * @generated from message meta.v1.UpdateMetadataResponse
 */
export type UpdateMetadataResponse = Message<"meta.v1.UpdateMetadataResponse"> & {
  /**
   * Resource identifier
   *
   * @generated from field: string resource_id = 1;
   */
  resourceId: string;

  /**
   * Updated metadata
   *
   * @generated from field: map<string, string> metadata = 2;
   */
  metadata: { [key: string]: string };

  /**
   * Operation success status
   *
   * @generated from field: bool success = 3;
   */
  success: boolean;
};

/**
 * Describes the message meta.v1.UpdateMetadataResponse.
 * Use `create(UpdateMetadataResponseSchema)` to create a new message.
 */
export const UpdateMetadataResponseSchema: GenMessage<UpdateMetadataResponse> = /*@__PURE__*/
  messageDesc(file_meta_v1_meta, 5);

/**
 * Status enum represents common status values for resources
 *
 * @generated from enum meta.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: STATUS_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: STATUS_DELETED = 3;
   */
  DELETED = 3,

  /**
   * @generated from enum value: STATUS_DRAFT = 4;
   */
  DRAFT = 4,

  /**
   * @generated from enum value: STATUS_PENDING = 5;
   */
  PENDING = 5,
}

/**
 * Describes the enum meta.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_meta_v1_meta, 0);

/**
 * MetadataService provides operations for metadata management
 *
 * @generated from service meta.v1.MetadataService
 */
export const MetadataService: GenService<{
  /**
   * GetMetadata retrieves metadata information
   *
   * @generated from rpc meta.v1.MetadataService.GetMetadata
   */
  getMetadata: {
    methodKind: "unary";
    input: typeof GetMetadataRequestSchema;
    output: typeof GetMetadataResponseSchema;
  },
  /**
   * UpdateMetadata modifies metadata 
   *
   * @generated from rpc meta.v1.MetadataService.UpdateMetadata
   */
  updateMetadata: {
    methodKind: "unary";
    input: typeof UpdateMetadataRequestSchema;
    output: typeof UpdateMetadataResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_meta_v1_meta, 0);

