// @generated by protoc-gen-connect-query v2.0.1
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import { ResourceService } from "./common_pb";

/**
 * GetResource fetches a resource by ID
 *
 * @generated from rpc common.v1.ResourceService.GetResource
 */
export const getResource: typeof ResourceService["method"]["getResource"];
/**
 * CreateResource stores a new resource
 *
 * @generated from rpc common.v1.ResourceService.CreateResource
 */
export const createResource: typeof ResourceService["method"]["createResource"];
/**
 * UpdateResource modifies an existing resource
 *
 * @generated from rpc common.v1.ResourceService.UpdateResource
 */
export const updateResource: typeof ResourceService["method"]["updateResource"];
/**
 * DeleteResource removes a resource
 *
 * @generated from rpc common.v1.ResourceService.DeleteResource
 */
export const deleteResource: typeof ResourceService["method"]["deleteResource"];
/**
 * ListResources fetches multiple resources
 *
 * @generated from rpc common.v1.ResourceService.ListResources
 */
export const listResources: typeof ResourceService["method"]["listResources"];
/**
 * QueryResources searches for resources matching criteria
 *
 * @generated from rpc common.v1.ResourceService.QueryResources
 */
export const queryResources: typeof ResourceService["method"]["queryResources"];
/**
 * BatchUpdateResources performs multiple operations in batch
 *
 * @generated from rpc common.v1.ResourceService.BatchUpdateResources
 */
export const batchUpdateResources: typeof ResourceService["method"]["batchUpdateResources"];
